databases:
  - name: knowledge_base
    databaseName: knowledge_base_production
    user: knowledge_base
    plan: free

services:
  - type: web
    name: knowledge_base
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: knowledge_base
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
